import { branchIdForName, CURRENT_SCHEMA_VERSION, demoBranches, demoOrganizationId } from "../domain/models";
import type { Branch, Organization, Appointment, AuditActivity, CrmDocument, Customer, Deal, DemoState, Employee, FinanceApplication, Lead, Payment, Quote, ServiceJob, TaskItem, TestDrive, Vehicle } from "../domain/models";
import { vehicleGalleries } from "../media/vehicleGalleries";

const NOW = "2026-08-16T08:00:00+02:00";
const at = (day: number, hour = 9) => `2026-08-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:00:00+02:00`;

const vehicleRows: Omit<Vehicle, "gallery" | "branchId">[] = [
  { id: "vehicle-01", stockId: "WEE-2401", vin: "WP0ZZZ99ZRS201001", year: 2024, make: "Porsche", model: "911", derivative: "GT3", price: 4_250_000, purchasePrice: 3_760_000, mileageKm: 3_800, exterior: "Chalk", branch: "Johannesburg North", location: "Showroom A", status: "Available", daysInStock: 18, bodyType: "Coupe", fuel: "Petrol", transmission: "Automatic", engine: "4.0L flat-six", registration: "MC 01 JN GP" },
  { id: "vehicle-02", stockId: "WEE-2402", vin: "WBS53AZ09PCM40202", year: 2023, make: "BMW", model: "M4", derivative: "CSL", price: 2_180_000, purchasePrice: 1_830_000, mileageKm: 8_450, exterior: "Frozen Grey", branch: "Sandton", location: "Showroom B", status: "Reserved", daysInStock: 11, bodyType: "Coupe", fuel: "Petrol", transmission: "Automatic", engine: "3.0L twin-turbo", registration: "MC 02 SD GP" },
  { id: "vehicle-03", stockId: "WEE-2403", vin: "WUAZZZF20RN603003", year: 2024, make: "Audi", model: "RS6", derivative: "Avant", price: 2_450_000, purchasePrice: 2_110_000, mileageKm: 1_250, exterior: "Nardo Grey", branch: "Pretoria", location: "Inbound Bay", status: "In Transit", daysInStock: 4, bodyType: "Wagon", fuel: "Petrol", transmission: "Automatic", engine: "4.0L V8 twin-turbo", registration: "MC 03 PT GP" },
  { id: "vehicle-04", stockId: "WEE-2404", vin: "SALCA2AU6RA704004", year: 2024, make: "Land Rover", model: "Defender", derivative: "110 D300", price: 1_980_000, purchasePrice: 1_640_000, mileageKm: 6_900, exterior: "Carpathian Grey", branch: "Midrand", location: "Showroom A", status: "Available", daysInStock: 27, bodyType: "SUV", fuel: "Diesel", transmission: "Automatic", engine: "3.0L turbodiesel", registration: "MC 04 MD GP" },
  { id: "vehicle-05", stockId: "WEE-2405", vin: "WP0ZZZY1ZRSA05005", year: 2024, make: "Porsche", model: "Taycan", derivative: "Turbo S", price: 3_150_000, purchasePrice: 2_760_000, mileageKm: 4_200, exterior: "Carmine Red", branch: "Johannesburg North", location: "Service Workshop", status: "Service Hold", daysInStock: 14, bodyType: "Sedan", fuel: "Electric", transmission: "Single-speed", engine: "Dual motor electric", registration: "MC 05 JN GP" },
  { id: "vehicle-06", stockId: "WEE-2406", vin: "W1K2060872R060006", year: 2024, make: "Mercedes-AMG", model: "C63", derivative: "S E Performance", price: 2_320_000, purchasePrice: 1_980_000, mileageKm: 2_750, exterior: "Obsidian Black", branch: "Sandton", location: "Showroom", status: "Available", daysInStock: 33, bodyType: "Sedan", fuel: "Plug-in Hybrid", transmission: "Automatic", engine: "2.0L turbo PHEV", registration: "MC 06 SD GP" },
  { id: "vehicle-07", stockId: "WEE-2407", vin: "JTKDB0C0XP3070007", year: 2023, make: "Toyota", model: "GR Supra", derivative: "3.0T", price: 1_150_000, purchasePrice: 920_000, mileageKm: 12_100, exterior: "Absolute White", branch: "Pretoria", location: "Showroom B", status: "Reserved", daysInStock: 8, bodyType: "Coupe", fuel: "Petrol", transmission: "Automatic", engine: "3.0L turbo", registration: "MC 07 PT GP" },
  { id: "vehicle-08", stockId: "WEE-2408", vin: "MPBCM2F60RX080008", year: 2024, make: "Ford", model: "Ranger", derivative: "Raptor", price: 1_420_000, purchasePrice: 1_180_000, mileageKm: 5_600, exterior: "Code Orange", branch: "Midrand", location: "Recon Bay", status: "Recon", daysInStock: 21, bodyType: "Double Cab", fuel: "Petrol", transmission: "Automatic", engine: "3.0L V6 twin-turbo", registration: "MC 08 MD GP" },
  { id: "vehicle-09", stockId: "WEE-2409", vin: "WVWZZZCDZRW090009", year: 2024, make: "Volkswagen", model: "Golf 8", derivative: "R", price: 1_060_000, purchasePrice: 850_000, mileageKm: 7_300, exterior: "Lapiz Blue", branch: "Johannesburg North", location: "Showroom", status: "Available", daysInStock: 39, bodyType: "Hatchback", fuel: "Petrol", transmission: "DCT", engine: "2.0L turbo", registration: "MC 09 JN GP" },
  { id: "vehicle-10", stockId: "WEE-2410", vin: "WBS13EU09R8X10010", year: 2024, make: "BMW", model: "X5 M", derivative: "Competition", price: 2_680_000, purchasePrice: 2_310_000, mileageKm: 1_900, exterior: "Marina Bay Blue", branch: "Sandton", location: "Photo Studio", status: "Photography", daysInStock: 3, bodyType: "SUV", fuel: "Petrol", transmission: "Automatic", engine: "4.4L V8 twin-turbo", registration: "MC 10 SD GP" },
  { id: "vehicle-11", stockId: "MCR-2511", vin: "MCRMDMA0000000011", year: 2023, make: "Mercedes-Benz", model: "GLE 53", derivative: "AMG Coupe", price: 1_899_900, purchasePrice: 1_615_000, mileageKm: 21_400, exterior: "Obsidian Black", branch: "Johannesburg North", location: "Main showroom", status: "Available", daysInStock: 46, bodyType: "SUV", fuel: "Petrol", transmission: "Automatic", engine: "3.0L turbo mild hybrid", registration: "MC 11 JN GP" },
  { id: "vehicle-12", stockId: "MCR-2512", vin: "MCRMDMA0000000012", year: 2024, make: "Toyota", model: "Land Cruiser 300", derivative: "ZX", price: 2_089_900, purchasePrice: 1_835_000, mileageKm: 9_800, exterior: "Pearl White", branch: "Pretoria", location: "Premium showroom", status: "Reserved", daysInStock: 17, bodyType: "SUV", fuel: "Diesel", transmission: "Automatic", engine: "3.3L V6 turbodiesel", registration: "MC 12 PT GP" },
  { id: "vehicle-13", stockId: "MCR-2513", vin: "MCRMDMA0000000013", year: 2023, make: "Hyundai", model: "Tucson", derivative: "N Line", price: 689_900, purchasePrice: 575_000, mileageKm: 18_600, exterior: "Titan Grey", branch: "Sandton", location: "Showroom floor", status: "Available", daysInStock: 29, bodyType: "SUV", fuel: "Petrol", transmission: "DCT", engine: "1.6L turbo", registration: "MC 13 SD GP" },
  { id: "vehicle-14", stockId: "MCR-2514", vin: "MCRMDMA0000000014", year: 2024, make: "Kia", model: "Sportage", derivative: "GT-Line", price: 759_900, purchasePrice: 645_000, mileageKm: 7_250, exterior: "Experience Green", branch: "Midrand", location: "Showroom floor", status: "Available", daysInStock: 12, bodyType: "SUV", fuel: "Petrol", transmission: "DCT", engine: "1.6L turbo", registration: "MC 14 MD GP" },
  { id: "vehicle-15", stockId: "MCR-2515", vin: "MCRMDMA0000000015", year: 2024, make: "Suzuki", model: "Jimny", derivative: "5-door GLX", price: 469_900, purchasePrice: 392_000, mileageKm: 4_900, exterior: "Kinetic Yellow", branch: "Pretoria", location: "Compact display", status: "Photography", daysInStock: 5, bodyType: "SUV", fuel: "Petrol", transmission: "Manual", engine: "1.5L petrol", registration: "MC 15 PT GP" },
  { id: "vehicle-16", stockId: "MCR-2516", vin: "MCRMDMA0000000016", year: 2023, make: "Nissan", model: "Navara", derivative: "Pro-4X", price: 829_900, purchasePrice: 705_000, mileageKm: 32_500, exterior: "Forged Metallic Copper", branch: "Johannesburg North", location: "Utility display", status: "Recon", daysInStock: 58, bodyType: "Double Cab", fuel: "Diesel", transmission: "Automatic", engine: "2.5L turbodiesel", registration: "MC 16 JN GP" },
  { id: "vehicle-17", stockId: "MCR-2517", vin: "MCRMDMA0000000017", year: 2024, make: "Mazda", model: "CX-60", derivative: "Takumi", price: 1_049_900, purchasePrice: 910_000, mileageKm: 6_400, exterior: "Soul Red Crystal", branch: "Sandton", location: "Premium showroom", status: "Available", daysInStock: 22, bodyType: "SUV", fuel: "Plug-in Hybrid", transmission: "Automatic", engine: "2.5L PHEV", registration: "MC 17 SD GP" },
  { id: "vehicle-18", stockId: "MCR-2518", vin: "MCRMDMA0000000018", year: 2023, make: "Volvo", model: "XC60", derivative: "Recharge Ultimate", price: 1_169_900, purchasePrice: 995_000, mileageKm: 14_300, exterior: "Crystal White", branch: "Midrand", location: "EV display", status: "Service Hold", daysInStock: 36, bodyType: "SUV", fuel: "Plug-in Hybrid", transmission: "Automatic", engine: "2.0L PHEV", registration: "MC 18 MD GP" },
  { id: "vehicle-19", stockId: "MCR-2519", vin: "MCRMDMA0000000019", year: 2024, make: "Range Rover", model: "Sport", derivative: "D350 Dynamic SE", price: 2_399_900, purchasePrice: 2_115_000, mileageKm: 8_100, exterior: "Santorini Black", branch: "Sandton", location: "Executive showroom", status: "Reserved", daysInStock: 41, bodyType: "SUV", fuel: "Diesel", transmission: "Automatic", engine: "3.0L turbodiesel", registration: "MC 19 SD GP" },
  { id: "vehicle-20", stockId: "MCR-2520", vin: "MCRMDMA0000000020", year: 2024, make: "Volkswagen", model: "Amarok", derivative: "Aventura", price: 1_249_900, purchasePrice: 1_065_000, mileageKm: 11_750, exterior: "Bright Beige Metallic", branch: "Johannesburg North", location: "Utility display", status: "Available", daysInStock: 31, bodyType: "Double Cab", fuel: "Diesel", transmission: "Automatic", engine: "3.0L V6 turbodiesel", registration: "MC 20 JN GP" },
  { id: "vehicle-21", stockId: "MCR-2521", vin: "MCRMDMA0000000021", year: 2024, make: "Ford", model: "Everest", derivative: "Platinum", price: 1_319_900, purchasePrice: 1_135_000, mileageKm: 13_200, exterior: "Equinox Bronze", branch: "Pretoria", location: "SUV showroom", status: "Photography", daysInStock: 9, bodyType: "SUV", fuel: "Diesel", transmission: "Automatic", engine: "3.0L V6 turbodiesel", registration: "MC 21 PT GP" },
  { id: "vehicle-22", stockId: "MCR-2522", vin: "MCRMDMA0000000022", year: 2023, make: "Audi", model: "Q5 Sportback", derivative: "45 TFSI quattro", price: 1_079_900, purchasePrice: 925_000, mileageKm: 19_500, exterior: "Glacier White", branch: "Midrand", location: "Premium showroom", status: "Available", daysInStock: 64, bodyType: "SUV", fuel: "Petrol", transmission: "Automatic", engine: "2.0L turbo", registration: "MC 22 MD GP" },
  { id: "vehicle-23", stockId: "MCR-2523", vin: "MCRMDMA0000000023", year: 2022, make: "BMW", model: "320i", derivative: "M Sport", price: 699_900, purchasePrice: 585_000, mileageKm: 38_400, exterior: "Portimao Blue", branch: "Johannesburg North", location: "Main showroom", status: "Available", daysInStock: 77, bodyType: "Sedan", fuel: "Petrol", transmission: "Automatic", engine: "2.0L turbo", registration: "MC 23 JN GP" },
  { id: "vehicle-24", stockId: "MCR-2524", vin: "MCRMDMA0000000024", year: 2023, make: "Mercedes-Benz", model: "V-Class", derivative: "V300d Exclusive", price: 1_849_900, purchasePrice: 1_590_000, mileageKm: 24_100, exterior: "Selenite Grey", branch: "Sandton", location: "Executive showroom", status: "Service Hold", daysInStock: 52, bodyType: "MPV", fuel: "Diesel", transmission: "Automatic", engine: "2.0L turbodiesel", registration: "MC 24 SD GP" },
  { id: "vehicle-25", stockId: "MCR-2525", vin: "MCRMDMA0000000025", year: 2024, make: "Toyota", model: "Corolla Cross", derivative: "GR-S", price: 579_900, purchasePrice: 486_000, mileageKm: 5_800, exterior: "Celestite Grey", branch: "Midrand", location: "Showroom floor", status: "Available", daysInStock: 14, bodyType: "SUV", fuel: "Petrol", transmission: "CVT", engine: "1.8L petrol", registration: "MC 25 MD GP" },
  { id: "vehicle-26", stockId: "MCR-2526", vin: "MCRMDMA0000000026", year: 2022, make: "Hyundai", model: "i20", derivative: "N", price: 529_900, purchasePrice: 438_000, mileageKm: 28_600, exterior: "Performance Blue", branch: "Pretoria", location: "Performance display", status: "Recon", daysInStock: 84, bodyType: "Hatchback", fuel: "Petrol", transmission: "Manual", engine: "1.6L turbo", registration: "MC 26 PT GP" },
  { id: "vehicle-27", stockId: "MCR-2527", vin: "MCRMDMA0000000027", year: 2023, make: "Kia", model: "Sorento", derivative: "SXL AWD", price: 989_900, purchasePrice: 835_000, mileageKm: 17_900, exterior: "Gravity Blue", branch: "Johannesburg North", location: "SUV showroom", status: "Available", daysInStock: 25, bodyType: "SUV", fuel: "Diesel", transmission: "Automatic", engine: "2.2L turbodiesel", registration: "MC 27 JN GP" },
  { id: "vehicle-28", stockId: "MCR-2528", vin: "MCRMDMA0000000028", year: 2024, make: "Nissan", model: "X-Trail", derivative: "e-Power Tekna", price: 849_900, purchasePrice: 720_000, mileageKm: 7_600, exterior: "Champagne Silver", branch: "Sandton", location: "Hybrid display", status: "Photography", daysInStock: 6, bodyType: "SUV", fuel: "Hybrid", transmission: "e-CVT", engine: "1.5L e-Power", registration: "MC 28 SD GP" },
  { id: "vehicle-29", stockId: "MCR-2529", vin: "MCRMDMA0000000029", year: 2023, make: "Mazda", model: "Mazda3", derivative: "Astina", price: 559_900, purchasePrice: 468_000, mileageKm: 16_300, exterior: "Machine Grey", branch: "Midrand", location: "Main showroom", status: "Available", daysInStock: 44, bodyType: "Hatchback", fuel: "Petrol", transmission: "Automatic", engine: "2.0L petrol", registration: "MC 29 MD GP" },
  { id: "vehicle-30", stockId: "MCR-2530", vin: "MCRMDMA0000000030", year: 2024, make: "Volvo", model: "XC40", derivative: "Recharge Twin", price: 1_099_900, purchasePrice: 935_000, mileageKm: 3_400, exterior: "Sage Green", branch: "Pretoria", location: "EV display", status: "Available", daysInStock: 10, bodyType: "SUV", fuel: "Electric", transmission: "Single-speed", engine: "Dual motor electric", registration: "MC 30 PT GP" },
];

const baseCustomers: Customer[] = [
  ["customer-01", "Amelia van Wyk", "amelia.vanwyk@example.com", "+264 81 410 2101", "Windhoek", "Active", "vehicle-01"], ["customer-02", "Jonas Kisting", "jonas.kisting@example.com", "+264 81 410 2102", "Windhoek", "Active", "vehicle-02"], ["customer-03", "Nadine Swart", "nadine.swart@example.com", "+264 81 410 2103", "Swakopmund", "Prospect", "vehicle-03"], ["customer-04", "Theo Beukes", "theo.beukes@example.com", "+264 81 410 2104", "Windhoek", "Active", "vehicle-04"], ["customer-05", "Karabo Molefe", "karabo.molefe@example.com", "+264 81 410 2105", "Walvis Bay", "Active", "vehicle-05"], ["customer-06", "Liam Pretorius", "liam.pretorius@example.com", "+264 81 410 2106", "Swakopmund", "Prospect", "vehicle-06"], ["customer-07", "Mia Hamutenya", "mia.hamutenya@example.com", "+264 81 410 2107", "Windhoek", "Active", "vehicle-07"], ["customer-08", "David Cloete", "david.cloete@example.com", "+264 81 410 2108", "Windhoek", "Prospect", "vehicle-08"], ["customer-09", "Elize Visser", "elize.visser@example.com", "+264 81 410 2109", "Swakopmund", "Active", "vehicle-09"], ["customer-10", "Tomas Ndjaba", "tomas.ndjaba@example.com", "+264 81 410 2110", "Windhoek", "Prospect", "vehicle-10"], ["customer-11", "Rene Jacobs", "rene.jacobs@example.com", "+264 81 410 2111", "Windhoek", "Active", "vehicle-01"], ["customer-12", "Sofia Mouton", "sofia.mouton@example.com", "+264 81 410 2112", "Walvis Bay", "Prospect", "vehicle-04"],
].map(([id, name, email, phone, city, crmStatus, vehicleInterestId], index) => ({ id, name, email, phone, city, crmStatus, vehicleInterestId, lastActivityAt: at(16, 8 + (index % 5)) }));

const extraCustomerNames = [
  "Lehlohonolo Maseko", "Bianca du Plessis", "Kagiso Modise", "Anika de Beer", "Tumelo Radebe", "Charné Fourie",
  "Mpho Mthembu", "Reabetswe Mokoena", "Keegan Adams", "Palesa Dube", "Ruan Botha", "Nokuthula Zulu",
  "Tshepo Mahlangu", "Simone Petersen", "Bongani Hadebe", "Danielle Smit", "Refilwe Moagi", "Luca Rossouw",
  "Lesedi Nkosi", "Taryn Williams", "Oarabile Sebego", "Heinrich Kruger", "Ayanda Cele", "Megan Daniels",
  "Katlego Matlala", "Johan Steyn", "Nandi Gumede", "Imraan Khan", "Busisiwe Mhlongo", "Francois Nel",
  "Neo Mokgosi", "Carmen September", "Lethabo Shabangu", "Waldo Coetzee", "Zinhle Mkhize", "Kian Jacobs",
] as const;
const customers: Customer[] = [
  ...baseCustomers,
  ...extraCustomerNames.map((name, index) => {
    const number = index + baseCustomers.length + 1;
    const slug = name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z]+/g, ".").replace(/(^\.|\.$)/g, "");
    return { id: `customer-${String(number).padStart(2, "0")}`, name, email: `${slug}@example.com`, phone: `+27 82 555 ${String(number).padStart(4, "0")}`, city: ["Johannesburg", "Sandton", "Pretoria", "Midrand"][index % 4], crmStatus: index % 3 ? "Active" : "Prospect", vehicleInterestId: `vehicle-${String((number - 1) % 30 + 1).padStart(2, "0")}`, lastActivityAt: at(16 + (index % 10), 8 + (index % 8)) };
  }),
];

const leads: Lead[] = Array.from({ length: 64 }, (_, index) => {
  const number = index + 1; const vehicleNumber = index < 16 ? (index % 10) + 1 : (index % 30) + 1; const customerNumber = index < 16 ? (index % 12) + 1 : (index % customers.length) + 1;
  const stages: Lead["stage"][] = ["Lead", "Negotiation", "Contract", "Delivery"];
  const tones: Lead["tone"][] = ["info", "warning", "positive", "neutral"];
  return { id: `lead-${String(number).padStart(2, "0")}`, customerId: `customer-${String(customerNumber).padStart(2, "0")}`, vehicleId: `vehicle-${String(vehicleNumber).padStart(2, "0")}`, owner: ["Naledi Ndlovu", "Alicia Brown", "Marcus Botha", "Lindiwe Khumalo"][index % 4], stage: stages[index % 4], value: vehicleRows[vehicleNumber - 1].price, nextAction: ["Call customer", "Confirm finance", "Send proposal", "Arrange delivery"][index % 4], dueAt: at(16 + (index % 5), 9 + (index % 4)), tone: tones[index % 4] };
});

const deals: Deal[] = Array.from({ length: 24 }, (_, index) => ({ id: `deal-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, salesRep: ["Naledi Ndlovu", "Marcus Botha", "Alicia Brown", "Lindiwe Khumalo"][index % 4], grossProfit: 95_000 + index * 12_500, status: (["Pending", "Approval", "Closed"] as const)[index % 3], date: at(12 + (index % 15)) }));

const serviceStatuses: ServiceJob["status"][] = ["Booked", "Checked In", "In Progress", "Waiting for Parts", "Quality Check", "Ready", "Completed"];
const serviceNotes = ["Annual inspection", "Pre-delivery inspection", "Software update", "Brake pad replacement", "Detail and polish", "Final quality check", "Completed handover inspection"];
const serviceJobs: ServiceJob[] = Array.from({ length: 18 }, (_, index) => ({ id: `service-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index % 46 + 3).padStart(2, "0")}`, vehicleId: `vehicle-${String((index + 3) % 30 + 1).padStart(2, "0")}`, advisor: index === 4 ? "Sipho Dlamini" : index % 2 ? "Sasha Naobes" : "Peter van der Merwe", technician: index % 2 ? "Elias //Garoeb" : "Marius Louw", status: serviceStatuses[index % serviceStatuses.length], dueAt: at(16 + (index % 12), 10), note: serviceNotes[index % serviceNotes.length] }));

const tasks: TaskItem[] = [
  ["task-01", "Call Amelia", "Confirm GT3 test drive", "lead", "lead-01", 16, "Due Today", "warning"], ["task-02", "Finance pack", "Submit M4 CSL application", "deal", "deal-02", 16, "Due Today", "info"], ["task-03", "Photograph X5 M", "Complete studio gallery", "vehicle", "vehicle-10", 17, "Upcoming", "neutral"], ["task-04", "Parts follow-up", "Confirm Taycan parts ETA", "service", "service-02", 15, "Overdue", "critical"], ["task-05", "RS6 arrival", "Inspect inbound delivery", "vehicle", "vehicle-03", 17, "Upcoming", "info"], ["task-06", "Delivery prep", "Schedule GR Supra handover", "lead", "lead-07", 18, "Upcoming", "positive"], ["task-07", "Approval review", "Review Defender margin", "deal", "deal-04", 16, "Due Today", "warning"], ["task-08", "Raptor recon", "Approve paint correction", "service", "service-05", 17, "Upcoming", "warning"], ["task-09", "Customer update", "Send Golf 8 R video", "lead", "lead-09", 15, "Completed", "positive"], ["task-10", "Contract signature", "Collect M4 CSL agreement", "lead", "lead-12", 16, "Due Today", "info"], ["task-11", "PDI booking", "Book C63 pre-delivery inspection", "service", "service-03", 18, "Upcoming", "neutral"], ["task-12", "Price review", "Review 911 GT3 listing", "vehicle", "vehicle-01", 19, "Upcoming", "info"],
].map(([id, title, detail, relatedType, relatedId, day, status, tone]) => ({ id: String(id), title: String(title), detail: String(detail), relatedType: relatedType as TaskItem["relatedType"], relatedId: String(relatedId), dueAt: at(day as number), status: status as TaskItem["status"], tone: tone as TaskItem["tone"] }));
for (let index = tasks.length; index < 40; index += 1) {
  const relatedType = (["lead", "deal", "vehicle", "service"] as const)[index % 4];
  const limits = { lead: leads.length, deal: deals.length, vehicle: vehicleRows.length, service: serviceJobs.length };
  const relatedId = `${relatedType === "service" ? "service" : relatedType}-${String(index % limits[relatedType] + 1).padStart(2, "0")}`;
  tasks.push({ id: `task-${String(index + 1).padStart(2, "0")}`, title: ["Customer follow-up", "Document review", "Stock check", "Workshop update"][index % 4], detail: `Connected ${relatedType} action ${index + 1}`, relatedType, relatedId, dueAt: at(16 + (index % 12), 8 + (index % 8)), status: index % 5 === 0 ? "Completed" : "Upcoming", tone: index % 5 === 0 ? "positive" : "info" });
}

const activities: AuditActivity[] = Array.from({ length: 40 }, (_, index) => { const kind = index % 4; const targetType = (["vehicle", "lead", "deal", "service"] as const)[kind]; const limits = { vehicle: vehicleRows.length, lead: leads.length, deal: deals.length, service: serviceJobs.length }; const targetId = `${targetType}-${String(index % limits[targetType] + 1).padStart(2, "0")}`; return { id: `activity-${String(index + 1).padStart(2, "0")}`, organizationId: demoOrganizationId, action: ["Vehicle updated", "Lead contacted", "Deal progressed", "Service note added"][kind], detail: `Demo activity ${index + 1} recorded for the employee workspace.`, actor: index % 2 ? "Marcus Botha" : "Alicia Brown", occurredAt: at(16 + (index % 12), 8 + (index % 10)), tone: (["info", "positive", "warning", "neutral"] as const)[kind], targetType, targetId }; });

const employeeRows: Array<[string, string, string, Employee["department"], string, string?]> = [
  ["owner", "Anele Dlamini", "Dealership Owner", "Executive", "Johannesburg North"], ["ceo", "Thandi Mokoena", "Group CEO", "Executive", "Sandton", "employee-01"],
  ["manager", "Jacques van der Merwe", "General Manager", "Executive", "Johannesburg North", "employee-01"], ["salesmanager", "Lindiwe Khumalo", "Sales Manager", "Sales", "Sandton", "employee-03"],
  ["sales", "Naledi Ndlovu", "Sales Executive", "Sales", "Johannesburg North", "employee-04"], ["finance", "Priya Naidoo", "F&I Manager", "Finance", "Sandton", "employee-03"],
  ["stock", "Kabelo Molefe", "Stock Controller", "Inventory", "Pretoria", "employee-03"], ["marketing", "Zanele Sithole", "Marketing Specialist", "Marketing", "Midrand", "employee-03"],
  ["accounts", "Ayesha Patel", "Accounts Clerk", "Accounts", "Johannesburg North", "employee-03"], ["employee", "Sipho Dlamini", "Service Coordinator", "Service", "Midrand", "employee-03"],
  ["auditor", "Mia Botha", "External Auditor", "Audit", "Johannesburg North"], ["sales-marcus", "Marcus Botha", "Sales Executive", "Sales", "Sandton", "employee-04"],
  ["sales-alicia", "Alicia Brown", "Sales Executive", "Sales", "Johannesburg North", "employee-04"], ["service-peter", "Peter van der Merwe", "Service Advisor", "Service", "Johannesburg North", "employee-03"],
  ["service-sasha", "Sasha Naobes", "Service Advisor", "Service", "Midrand", "employee-03"],
];
const employees: Employee[] = employeeRows.map(([accountId, name, title, department, branch, managerId], index) => ({ id: `employee-${String(index + 1).padStart(2, "0")}`, accountId, name, email: `${accountId}@motorcrm.demo`, title, department, branch, branchId: branchIdForName(demoOrganizationId, branch), managerId, status: index === 14 ? "Leave" : "Active" }));

const appointments: Appointment[] = Array.from({ length: 24 }, (_, index) => ({ id: `appointment-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, leadId: `lead-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, assignedTo: ["Naledi Ndlovu", "Marcus Botha", "Alicia Brown", "Lindiwe Khumalo"][index % 4], branch: vehicleRows[index % 30].branch, branchId: branchIdForName(demoOrganizationId, vehicleRows[index % 30].branch), scheduledAt: at(17 + (index % 10), 8 + (index % 8)), purpose: (["Consultation", "Finance Review", "Delivery", "Service Handover"] as const)[index % 4], status: (["Scheduled", "Confirmed", "Completed", "Cancelled"] as const)[index % 4] }));
const testDrives: TestDrive[] = Array.from({ length: 16 }, (_, index) => ({ id: `test-drive-${String(index + 1).padStart(2, "0")}`, appointmentId: `appointment-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, leadId: `lead-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, host: ["Naledi Ndlovu", "Marcus Botha", "Alicia Brown", "Lindiwe Khumalo"][index % 4], scheduledAt: appointments[index].scheduledAt, status: (["Booked", "Completed", "No Show"] as const)[index % 3], outcome: ["Awaiting drive", "Customer requested a quote", "Follow-up required"][index % 3] }));
const quotes: Quote[] = Array.from({ length: 24 }, (_, index) => ({ id: `quote-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, leadId: `lead-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, createdBy: ["Naledi Ndlovu", "Marcus Botha", "Alicia Brown", "Lindiwe Khumalo"][index % 4], amount: vehicleRows[index % 30].price, status: (["Draft", "Sent", "Accepted", "Expired"] as const)[index % 4], createdAt: at(12 + (index % 12)), expiresAt: at(20 + (index % 8)) }));
const payments: Payment[] = Array.from({ length: 18 }, (_, index) => ({ id: `payment-${String(index + 1).padStart(2, "0")}`, dealId: `deal-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, amount: index % 3 === 1 ? vehicleRows[index % 30].price - 100_000 : 100_000 + index * 5_000, kind: (["Deposit", "Balance", "Refund"] as const)[index % 3], status: (["Pending", "Cleared", "Failed"] as const)[index % 3], paidAt: at(13 + (index % 12), 10) }));
const financeApplications: FinanceApplication[] = Array.from({ length: 20 }, (_, index) => ({ id: `finance-application-${String(index + 1).padStart(2, "0")}`, dealId: `deal-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, owner: "Priya Naidoo", requestedAmount: Math.round(vehicleRows[index % 30].price * 0.82), status: (["Draft", "Submitted", "Approved", "Declined"] as const)[index % 4], updatedAt: at(14 + (index % 12), 11) }));
const documents: CrmDocument[] = Array.from({ length: 30 }, (_, index) => ({ id: `document-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index % customers.length + 1).padStart(2, "0")}`, leadId: index < 24 ? `lead-${String(index + 1).padStart(2, "0")}` : undefined, dealId: index < 20 ? `deal-${String(index + 1).padStart(2, "0")}` : undefined, vehicleId: `vehicle-${String(index % 30 + 1).padStart(2, "0")}`, name: ["Identity document", "Vehicle quotation", "Finance consent", "Sale agreement", "Delivery checklist", "Service record"][index % 6], category: (["Identity", "Quote", "Finance", "Contract", "Delivery", "Service"] as const)[index % 6], status: (["Required", "Uploaded", "Verified", "Expired"] as const)[index % 4], updatedAt: at(15 + (index % 12), 9) }));

const copyGallery = (vehicleId: string) => {
  const gallery = vehicleGalleries[vehicleId];
  return { ...gallery, images: gallery.images.map((image) => ({ ...image })) };
};

const organizations: Organization[] = [{ id: demoOrganizationId, name: "MotorGroup South Africa", tradingName: "MotorCRM Demo Group" }];
const branches: Branch[] = demoBranches.map((name) => ({ id: branchIdForName(demoOrganizationId, name), organizationId: demoOrganizationId, name }));

export function createSeedState(): DemoState {
  const vehicles = vehicleRows.map((vehicle) => ({ ...vehicle, branchId: branchIdForName(demoOrganizationId, vehicle.branch), gallery: copyGallery(vehicle.id) }));
  const financedVehicleIndexes = [1, 0, ...Array.from({ length: 18 }, (_, index) => index + 2)];
  const financeDrafts = financedVehicleIndexes.map((vehicleIndex, index) => ({ vehicleId: `vehicle-${String(vehicleIndex + 1).padStart(2, "0")}`, vehiclePrice: vehicleRows[vehicleIndex].price, downPayment: index === 0 ? 350_000 : 150_000 + index * 10_000, termMonths: ([60, 48, 60, 72] as const)[index % 4], aprPercent: index === 0 ? 11.5 : 9.5 + (index % 6) * .75, tradeAllowance: index === 0 ? 280_000 : index % 3 ? 0 : 220_000, lienPayoff: index === 0 ? 90_000 : 0, serviceContract: index === 0 ? 32_000 : 18_000 + index * 500, gapInsurance: index === 0 ? 14_500 : 9_500 }));
  return { schemaVersion: CURRENT_SCHEMA_VERSION, sessions: [], organizations: organizations.map((organization) => ({ ...organization })), branches: branches.map((branch) => ({ ...branch })), vehicles, customers: customers.map((customer) => ({ ...customer })), leads: leads.map((lead) => ({ ...lead })), deals: deals.map((deal) => ({ ...deal })), financeDrafts, financeApplications: financeApplications.map((application) => ({ ...application })), serviceJobs: serviceJobs.map((job) => ({ ...job })), employees: employees.map((employee) => ({ ...employee })), appointments: appointments.map((appointment) => ({ ...appointment })), testDrives: testDrives.map((testDrive) => ({ ...testDrive })), quotes: quotes.map((quote) => ({ ...quote })), payments: payments.map((payment) => ({ ...payment })), documents: documents.map((document) => ({ ...document })), tasks: tasks.map((task) => ({ ...task })), notifications: [
    { id: "notification-01", organizationId: demoOrganizationId, category: "deal", priority: "normal", title: "M4 CSL reserved", detail: "Deposit received from Jonas Kisting.", read: false, tone: "positive", createdAt: at(16, 8), relatedId: "deal-02" },
    { id: "notification-02", organizationId: demoOrganizationId, category: "service", priority: "normal", title: "Taycan parts delayed", detail: "Rear sensor delivery moved to Tuesday.", read: false, tone: "warning", createdAt: at(15, 14), relatedId: "service-02" },
    { id: "notification-03", organizationId: demoOrganizationId, category: "inventory", priority: "normal", title: "RS6 inbound", detail: "Carrier has checked in at the branch.", read: true, tone: "info", createdAt: at(15, 11), relatedId: "vehicle-03" },
    { id: "notification-04", organizationId: demoOrganizationId, category: "deal", priority: "high", title: "Approval required", detail: "Defender deal needs margin approval.", read: false, tone: "critical", createdAt: at(16, 7), relatedId: "deal-04" },
    { id: "notification-05", organizationId: demoOrganizationId, category: "inventory", priority: "normal", title: "Gallery ready", detail: "Golf 8 R images have been uploaded.", read: true, tone: "positive", createdAt: at(14, 16), relatedId: "vehicle-09" },
    { id: "notification-06", organizationId: demoOrganizationId, category: "lead", priority: "normal", title: "New lead", detail: "A customer requested a GT3 callback.", read: false, tone: "info", createdAt: at(16, 9), relatedId: "lead-01" },
  ], activities: activities.map((activity) => ({ ...activity })), preferences: { branch: "Johannesburg North", density: "comfortable", activePage: "my-day", activeSubview: "overview", viewPreferences: { inventory: { query: "", status: "All", mode: "cards" }, customers: { query: "", status: "All", tab: "overview" }, sales: { query: "", status: "All", sort: "date" }, service: { query: "", filter: "All", view: "Board" } } }, drafts: { vehicleIntake: null, vehicleIntakes: {}, lead: null, deal: null, serviceNotes: {} } };
}

export { NOW };
