import type { AuditActivity, Customer, Deal, DemoState, Lead, ServiceJob, TaskItem, Vehicle } from "../domain/models";
import { vehicleGalleries } from "../media/vehicleGalleries";

const NOW = "2026-08-16T08:00:00+02:00";
const at = (day: number, hour = 9) => `2026-08-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:00:00+02:00`;

const vehicleRows: Omit<Vehicle, "gallery">[] = [
  { id: "vehicle-01", stockId: "WEE-2401", vin: "WP0ZZZ99ZRS201001", year: 2024, make: "Porsche", model: "911", derivative: "GT3", price: 4_250_000, purchasePrice: 3_760_000, mileageKm: 3_800, exterior: "Chalk", branch: "Windhoek", location: "Showroom A", status: "Available", daysInStock: 18 },
  { id: "vehicle-02", stockId: "WEE-2402", vin: "WBS53AZ09PCM40202", year: 2023, make: "BMW", model: "M4", derivative: "CSL", price: 2_180_000, purchasePrice: 1_830_000, mileageKm: 8_450, exterior: "Frozen Grey", branch: "Windhoek", location: "Showroom B", status: "Reserved", daysInStock: 11 },
  { id: "vehicle-03", stockId: "WEE-2403", vin: "WUAZZZF20RN603003", year: 2024, make: "Audi", model: "RS6", derivative: "Avant", price: 2_450_000, purchasePrice: 2_110_000, mileageKm: 1_250, exterior: "Nardo Grey", branch: "Swakopmund", location: "Inbound Bay", status: "In Transit", daysInStock: 4 },
  { id: "vehicle-04", stockId: "WEE-2404", vin: "SALCA2AU6RA704004", year: 2024, make: "Land Rover", model: "Defender", derivative: "110 D300", price: 1_980_000, purchasePrice: 1_640_000, mileageKm: 6_900, exterior: "Carpathian Grey", branch: "Windhoek", location: "Showroom A", status: "Available", daysInStock: 27 },
  { id: "vehicle-05", stockId: "WEE-2405", vin: "WP0ZZZY1ZRSA05005", year: 2024, make: "Porsche", model: "Taycan", derivative: "Turbo S", price: 3_150_000, purchasePrice: 2_760_000, mileageKm: 4_200, exterior: "Carmine Red", branch: "Windhoek", location: "Service Workshop", status: "Service Hold", daysInStock: 14 },
  { id: "vehicle-06", stockId: "WEE-2406", vin: "W1K2060872R060006", year: 2024, make: "Mercedes-AMG", model: "C63", derivative: "S E Performance", price: 2_320_000, purchasePrice: 1_980_000, mileageKm: 2_750, exterior: "Obsidian Black", branch: "Swakopmund", location: "Showroom", status: "Available", daysInStock: 33 },
  { id: "vehicle-07", stockId: "WEE-2407", vin: "JTKDB0C0XP3070007", year: 2023, make: "Toyota", model: "GR Supra", derivative: "3.0T", price: 1_150_000, purchasePrice: 920_000, mileageKm: 12_100, exterior: "Absolute White", branch: "Windhoek", location: "Showroom B", status: "Reserved", daysInStock: 8 },
  { id: "vehicle-08", stockId: "WEE-2408", vin: "MPBCM2F60RX080008", year: 2024, make: "Ford", model: "Ranger", derivative: "Raptor", price: 1_420_000, purchasePrice: 1_180_000, mileageKm: 5_600, exterior: "Code Orange", branch: "Windhoek", location: "Recon Bay", status: "Recon", daysInStock: 21 },
  { id: "vehicle-09", stockId: "WEE-2409", vin: "WVWZZZCDZRW090009", year: 2024, make: "Volkswagen", model: "Golf 8", derivative: "R", price: 1_060_000, purchasePrice: 850_000, mileageKm: 7_300, exterior: "Lapiz Blue", branch: "Swakopmund", location: "Showroom", status: "Available", daysInStock: 39 },
  { id: "vehicle-10", stockId: "WEE-2410", vin: "WBS13EU09R8X10010", year: 2024, make: "BMW", model: "X5 M", derivative: "Competition", price: 2_680_000, purchasePrice: 2_310_000, mileageKm: 1_900, exterior: "Marina Bay Blue", branch: "Windhoek", location: "Photo Studio", status: "Photography", daysInStock: 3 },
];

const customers: Customer[] = [
  ["customer-01", "Amelia van Wyk", "amelia.vanwyk@example.com", "+264 81 410 2101", "Windhoek", "Active", "vehicle-01"], ["customer-02", "Jonas Kisting", "jonas.kisting@example.com", "+264 81 410 2102", "Windhoek", "Active", "vehicle-02"], ["customer-03", "Nadine Swart", "nadine.swart@example.com", "+264 81 410 2103", "Swakopmund", "Prospect", "vehicle-03"], ["customer-04", "Theo Beukes", "theo.beukes@example.com", "+264 81 410 2104", "Windhoek", "Active", "vehicle-04"], ["customer-05", "Karabo Molefe", "karabo.molefe@example.com", "+264 81 410 2105", "Walvis Bay", "Active", "vehicle-05"], ["customer-06", "Liam Pretorius", "liam.pretorius@example.com", "+264 81 410 2106", "Swakopmund", "Prospect", "vehicle-06"], ["customer-07", "Mia Hamutenya", "mia.hamutenya@example.com", "+264 81 410 2107", "Windhoek", "Active", "vehicle-07"], ["customer-08", "David Cloete", "david.cloete@example.com", "+264 81 410 2108", "Windhoek", "Prospect", "vehicle-08"], ["customer-09", "Elize Visser", "elize.visser@example.com", "+264 81 410 2109", "Swakopmund", "Active", "vehicle-09"], ["customer-10", "Tomas Ndjaba", "tomas.ndjaba@example.com", "+264 81 410 2110", "Windhoek", "Prospect", "vehicle-10"], ["customer-11", "Rene Jacobs", "rene.jacobs@example.com", "+264 81 410 2111", "Windhoek", "Active", "vehicle-01"], ["customer-12", "Sofia Mouton", "sofia.mouton@example.com", "+264 81 410 2112", "Walvis Bay", "Prospect", "vehicle-04"],
].map(([id, name, email, phone, city, crmStatus, vehicleInterestId], index) => ({ id, name, email, phone, city, crmStatus, vehicleInterestId, lastActivityAt: at(16, 8 + (index % 5)) }));

const leads: Lead[] = Array.from({ length: 16 }, (_, index) => {
  const number = index + 1; const vehicleNumber = (index % 10) + 1; const customerNumber = (index % 12) + 1;
  const stages: Lead["stage"][] = ["Lead", "Negotiation", "Contract", "Delivery"];
  const tones: Lead["tone"][] = ["info", "warning", "positive", "neutral"];
  return { id: `lead-${String(number).padStart(2, "0")}`, customerId: `customer-${String(customerNumber).padStart(2, "0")}`, vehicleId: `vehicle-${String(vehicleNumber).padStart(2, "0")}`, owner: number % 2 ? "Alicia Brown" : "Marcus Botha", stage: stages[index % 4], value: vehicleRows[vehicleNumber - 1].price, nextAction: ["Call customer", "Confirm finance", "Send proposal", "Arrange delivery"][index % 4], dueAt: at(16 + (index % 5), 9 + (index % 4)), tone: tones[index % 4] };
});

const deals: Deal[] = Array.from({ length: 8 }, (_, index) => ({ id: `deal-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 1).padStart(2, "0")}`, vehicleId: `vehicle-${String(index + 1).padStart(2, "0")}`, salesRep: index % 2 ? "Marcus Botha" : "Alicia Brown", grossProfit: 95_000 + index * 12_500, status: (["Pending", "Approval", "Closed"] as const)[index % 3], date: at(12 + index) }));

const serviceJobs: ServiceJob[] = Array.from({ length: 6 }, (_, index) => ({ id: `service-${String(index + 1).padStart(2, "0")}`, customerId: `customer-${String(index + 3).padStart(2, "0")}`, vehicleId: `vehicle-${String(index + 4).padStart(2, "0")}`, advisor: index % 2 ? "Sasha Naobes" : "Peter van der Merwe", technician: index % 2 ? "Elias //Garoeb" : "Marius Louw", status: (["Booked", "Checked In", "In Progress", "Waiting for Parts", "Quality Check", "Ready"] as const)[index], dueAt: at(16 + index, 10), note: ["Annual inspection", "Pre-delivery inspection", "Software update", "Brake pad replacement", "Detail and polish", "Final quality check"][index] }));

const tasks: TaskItem[] = [
  ["task-01", "Call Amelia", "Confirm GT3 test drive", "lead", "lead-01", 16, "Due Today", "warning"], ["task-02", "Finance pack", "Submit M4 CSL application", "deal", "deal-02", 16, "Due Today", "info"], ["task-03", "Photograph X5 M", "Complete studio gallery", "vehicle", "vehicle-10", 17, "Upcoming", "neutral"], ["task-04", "Parts follow-up", "Confirm Taycan parts ETA", "service", "service-02", 15, "Overdue", "critical"], ["task-05", "RS6 arrival", "Inspect inbound delivery", "vehicle", "vehicle-03", 17, "Upcoming", "info"], ["task-06", "Delivery prep", "Schedule GR Supra handover", "lead", "lead-07", 18, "Upcoming", "positive"], ["task-07", "Approval review", "Review Defender margin", "deal", "deal-04", 16, "Due Today", "warning"], ["task-08", "Raptor recon", "Approve paint correction", "service", "service-05", 17, "Upcoming", "warning"], ["task-09", "Customer update", "Send Golf 8 R video", "lead", "lead-09", 15, "Completed", "positive"], ["task-10", "Contract signature", "Collect M4 CSL agreement", "lead", "lead-12", 16, "Due Today", "info"], ["task-11", "PDI booking", "Book C63 pre-delivery inspection", "service", "service-03", 18, "Upcoming", "neutral"], ["task-12", "Price review", "Review 911 GT3 listing", "vehicle", "vehicle-01", 19, "Upcoming", "info"],
].map(([id, title, detail, relatedType, relatedId, day, status, tone]) => ({ id: String(id), title: String(title), detail: String(detail), relatedType: relatedType as TaskItem["relatedType"], relatedId: String(relatedId), dueAt: at(day as number), status: status as TaskItem["status"], tone: tone as TaskItem["tone"] }));

const activities: AuditActivity[] = Array.from({ length: 12 }, (_, index) => ({ id: `activity-${String(index + 1).padStart(2, "0")}`, action: ["Vehicle updated", "Lead contacted", "Deal progressed", "Service note added"][index % 4], detail: `Demo activity ${index + 1} recorded for the employee workspace.`, actor: index % 2 ? "Marcus Botha" : "Alicia Brown", occurredAt: at(16, 8 + index), tone: (["info", "positive", "warning", "neutral"] as const)[index % 4] }));

export function createSeedState(): DemoState {
  const vehicles = vehicleRows.map((vehicle) => ({ ...vehicle, gallery: vehicleGalleries[vehicle.id] }));
  return { schemaVersion: 1, vehicles, customers, leads, deals, financeDrafts: [{ vehicleId: "vehicle-02", vehiclePrice: 2_180_000, downPayment: 350_000, termMonths: 60, aprPercent: 11.5, tradeAllowance: 280_000, lienPayoff: 90_000, serviceContract: 32_000, gapInsurance: 14_500 }], serviceJobs, tasks, notifications: [
    { id: "notification-01", title: "M4 CSL reserved", detail: "Deposit received from Jonas Kisting.", read: false, tone: "positive", relatedId: "deal-02" }, { id: "notification-02", title: "Taycan parts delayed", detail: "Rear sensor delivery moved to Tuesday.", read: false, tone: "warning", relatedId: "service-02" }, { id: "notification-03", title: "RS6 inbound", detail: "Carrier has checked in at the branch.", read: true, tone: "info", relatedId: "vehicle-03" }, { id: "notification-04", title: "Approval required", detail: "Defender deal needs margin approval.", read: false, tone: "critical", relatedId: "deal-04" }, { id: "notification-05", title: "Gallery ready", detail: "Golf 8 R images have been uploaded.", read: true, tone: "positive", relatedId: "vehicle-09" }, { id: "notification-06", title: "New lead", detail: "A customer requested a GT3 callback.", read: false, tone: "info", relatedId: "lead-01" },
  ], activities, preferences: { branch: "Windhoek", density: "comfortable", activePage: "Dashboard", activeSubview: "Overview" }, drafts: { vehicleIntake: null, lead: null, deal: null, serviceNotes: {} } };
}

export { NOW };
