import { useMemo, useState } from "react";
import type { Customer, DemoState, ViewPreferences } from "../../domain/models";
import type { DemoRepository } from "../../repository/demoRepository";
import { Button } from "../../components/controls/Button";
import { StatusPill } from "../../components/controls/StatusPill";
import { RecordTable } from "../../components/data-display/RecordTable";
import { Tabs } from "../../components/controls/Tabs";

const newId = () => `customer-${crypto.randomUUID?.() ?? Date.now()}`;
const defaults: ViewPreferences["customers"] = { query: "", status: "All", tab: "overview" };
type Props = { state: DemoState; repository: DemoRepository; onOpenCustomer?: (customerId: string) => void; viewPreferences?: ViewPreferences["customers"]; onViewPreferencesChange?: (patch: Partial<ViewPreferences["customers"]>) => void; canWrite?: boolean };

export function CustomersPage({ state, repository, onOpenCustomer, viewPreferences, onViewPreferencesChange, canWrite = true }: Props) {
  const [fallback, setFallback] = useState(defaults); const { query, status, tab } = viewPreferences ?? fallback;
  const changeView = (patch: Partial<ViewPreferences["customers"]>) => { if (!viewPreferences) setFallback((current) => ({ ...current, ...patch })); onViewPreferencesChange?.(patch); };
  const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", email: "", phone: "", city: "Windhoek", vehicleInterestId: state.vehicles[0]?.id ?? "" });
  const rows = useMemo(() => state.customers.filter((customer) => (status === "All" || customer.crmStatus === status) && `${customer.name} ${customer.email} ${customer.phone} ${customer.city}`.toLowerCase().includes(query.toLowerCase())), [query, state.customers, status]);
  const addCustomer = () => { setError(""); if (!form.name.trim() || !form.email.trim()) { setError("Enter the customer name and email address before saving."); return; } try { repository.addCustomer({ id: newId(), ...form, crmStatus: "Prospect", lastActivityAt: new Date().toISOString() }); setCreating(false); setForm({ name: "", email: "", phone: "", city: "Windhoek", vehicleInterestId: state.vehicles[0]?.id ?? "" }); } catch (reason) { setError(reason instanceof Error ? reason.message : "The customer could not be saved."); } };
  const directory = <RecordTable caption="Customer directory" records={rows} emptyMessage="No customers match these filters." columns={[{ key: "customer", label: "Customer", render: (customer: Customer) => <button className="inventory-record-link" onClick={() => onOpenCustomer?.(customer.id)}><strong>{customer.name}</strong><small>{customer.email} · {customer.phone || "No phone recorded"}</small></button> }, { key: "interest", label: "Interest", render: (customer: Customer) => { const vehicle = state.vehicles.find((item) => item.id === customer.vehicleInterestId); return vehicle ? `${vehicle.year} ${vehicle.make} ${vehicle.model}` : "No vehicle assigned"; } }, { key: "status", label: "Status", render: (customer: Customer) => <StatusPill tone={customer.crmStatus === "Active" ? "positive" : "info"}>{customer.crmStatus}</StatusPill> }, { key: "followup", label: "Next follow-up", render: (customer: Customer) => state.leads.find((lead) => lead.customerId === customer.id)?.nextAction ?? "No open follow-up" }]} />;
  const followups = <ul className="action-centre-list">{state.leads.filter((lead) => rows.some((customer) => customer.id === lead.customerId)).map((lead) => { const customer = state.customers.find((item) => item.id === lead.customerId)!; return <li key={lead.id}><div><strong>{customer.name}</strong><p>{lead.nextAction} · {lead.stage}</p></div><Button variant="secondary" onClick={() => onOpenCustomer?.(customer.id)}>Open customer</Button></li>; })}</ul>;
  return <section className="crm-page customers-page" aria-labelledby="customers-title">
    <header className="crm-heading"><div><p className="crm-eyebrow">CRM directory</p><h1 id="customers-title">Customers</h1><p>Ownership, interests, and every next conversation in one connected directory.</p></div>{canWrite ? <Button onClick={() => setCreating((value) => !value)} aria-expanded={creating}>{creating ? "Close form" : "Create customer"}</Button> : null}</header>
    {creating && canWrite ? <form className="crm-form" onSubmit={(event) => { event.preventDefault(); addCustomer(); }} noValidate><h2>New customer</h2>{error && <p className="form-error" role="alert">{error}</p>}<label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label>Phone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>City<input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} /></label><label>Vehicle interest<select value={form.vehicleInterestId} onChange={(event) => setForm({ ...form, vehicleInterestId: event.target.value })}>{state.vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.year} {vehicle.make} {vehicle.model}</option>)}</select></label><Button type="submit">Save customer</Button></form> : null}
    <div className="crm-toolbar" data-tour="customers-toolbar"><label>Search customers<input value={query} onChange={(event) => changeView({ query: event.target.value })} placeholder="Name, email, phone or city" /></label><label>Status<select value={status} onChange={(event) => changeView({ status: event.target.value as ViewPreferences["customers"]["status"] })}><option>All</option><option>Active</option><option>Prospect</option></select></label></div>
    <Tabs label="Customer directory views" activeId={tab} onChange={(next) => changeView({ tab: next })} items={[{ id: "overview", label: "Overview", panel: directory }, { id: "follow-ups", label: "Follow-ups", panel: followups }]} />
  </section>;
}
