import { useState } from "react";
import type { Deal, DemoState } from "../../domain/models";
import type { DemoRepository } from "../../repository/demoRepository";
import { Button } from "../../components/controls/Button";

const nextDealId = (state: DemoState) => `deal-${String(Math.max(0, ...state.deals.map((deal) => Number(deal.id.match(/\d+$/)?.[0] ?? 0))) + 1).padStart(2, "0")}`;

export function DealEntry({ state, repository, initialVehicleId, defaultSalesRep = "Alicia Brown", lockSalesRep = false, onCreated, title = "New deal" }: { state: DemoState; repository: DemoRepository; initialVehicleId?: string; defaultSalesRep?: string; lockSalesRep?: boolean; onCreated?: (deal: Deal) => void; title?: string }) {
  const vehicleId = initialVehicleId && state.vehicles.some((vehicle) => vehicle.id === initialVehicleId) ? initialVehicleId : state.vehicles[0]?.id ?? "";
  const customerId = state.customers.find((customer) => customer.vehicleInterestId === vehicleId)?.id ?? state.customers[0]?.id ?? "";
  const [error, setError] = useState("");
  const [form, setForm] = useState({ customerId, vehicleId, salesRep: defaultSalesRep, grossProfit: "0", status: "Pending" as Deal["status"] });
  const create = () => { setError(""); const grossProfit = Number(form.grossProfit); const salesRep = lockSalesRep ? defaultSalesRep : form.salesRep.trim(); if (!form.customerId || !form.vehicleId || !salesRep || !Number.isFinite(grossProfit)) { setError("Choose a customer and vehicle, enter a sales rep, and provide a valid gross profit."); return; } try { const deal: Deal = { id: nextDealId(repository.getState()), customerId: form.customerId, vehicleId: form.vehicleId, salesRep, grossProfit, status: form.status, date: new Date().toISOString() }; repository.addDeal(deal); onCreated?.(deal); } catch (reason) { setError(reason instanceof Error ? reason.message : "The deal could not be saved."); } };
  return <form className="crm-form" onSubmit={(event) => { event.preventDefault(); create(); }} noValidate><h2>{title}</h2>{error && <p className="form-error" role="alert">{error}</p>}<label>Customer<select value={form.customerId} onChange={(event) => setForm({ ...form, customerId: event.target.value })}>{state.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label>Vehicle<select value={form.vehicleId} onChange={(event) => setForm({ ...form, vehicleId: event.target.value })}>{state.vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.year} {vehicle.make} {vehicle.model} {vehicle.derivative}</option>)}</select></label><label>Sales rep<input value={lockSalesRep ? defaultSalesRep : form.salesRep} onChange={(event) => setForm({ ...form, salesRep: event.target.value })} readOnly={lockSalesRep} required /></label><label>Gross profit (ZAR)<input type="number" value={form.grossProfit} onChange={(event) => setForm({ ...form, grossProfit: event.target.value })} required /></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Deal["status"] })}><option>Pending</option><option>Approval</option><option>Closed</option></select></label><Button type="submit">Save deal</Button></form>;
}
